# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import user_pb2 as user__pb2


class UserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/oChat.main.grpc.user.User/CreateUser',
        request_serializer=user__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=user__pb2.CreateUserResponse.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/oChat.main.grpc.user.User/GetUser',
        request_serializer=user__pb2.GetUserRequest.SerializeToString,
        response_deserializer=user__pb2.GetUserResponse.FromString,
        )


class UserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=user__pb2.CreateUserRequest.FromString,
          response_serializer=user__pb2.CreateUserResponse.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__pb2.GetUserRequest.FromString,
          response_serializer=user__pb2.GetUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'oChat.main.grpc.user.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
